feat: support dotenv-safe's allow-empty-values
peerigon/dotenv-safe-action pull request #1
Opened 2021-12-06 10:29 UTC by tannerbaum

https://www.npmjs.com/package/dotenv-safe#allowemptyvalues

2021-12-06 10:38 UTC, tannerbaum commented
ugh need to build it before merging and git is not cooperating

2021-12-07 08:08 UTC, hpohlmeyer requested changes

2021-12-07 08:08 UTC, hpohlmeyer commented on dist/index.js
> +const parseEnv = (envPath, examplePath, allowEmpty = "false") => {
Having a stringified boolean here is a little weird, what do you think of changing this to a boolean and do the boolean conversion before calling the function.

2021-12-07 08:08 UTC, hpohlmeyer commented on dist/index.js
> +            const allowEmpty = core.getInput('allow-empty-values');
What do you think about casting it to a boolean right here and throwing a meaningful error if that fails. This way we get proper error handling and can use it as a boolean for the rest of the script.

2021-12-07 09:18 UTC, hpohlmeyer approved these changes

2021-12-07 09:19 UTC, merged